### ISSUE TITLE
[wish] CI

### ISSUE THREAD

**Issue by gares** [proofcert/fpc-elpi#2]
Given the complexity of the tool chain I suggest you set up CI to be sure things work with the advertised setup. This is what we do for HB:

https://github.com/math-comp/hierarchy-builder/blob/f4e5bd8f5fc74e34f9e7818c42c80494074e7018/.travis.yml#L28-L52

You also need the scripts in `.travis/` and customize the value of CMD

Hope it helps

**Comment by gares** [comment]
After having written this message I forgot we have a fix for the scripts in the branch we are currently working on. You have to add `set -e` to the scripts in `.travis/` otherwise travis reports success even if docker fails.

**Comment by robblanco** [comment]
This is very true, Enrico, thank you for the suggestion. I have been experimenting with Coq CI options over the past two weekends and considering either Travis or CircleCI after a look at GitHub Actions, which seem less performant. Are there any particular reasons for you to use Travis over any of the alternatives?

**Comment by gares** [comment]
no, I just happen to know it a little and there is some doc/howto in coq-community

**Comment by robblanco** [comment]
Perfect, thank you again. We can add CI for sure, and that howto you mention together with your own setup will be good references.

**Comment by manmatteo** [comment]
Fixed since 696b83baf2ee41178d2ea4e9ec11fc9268e0190b
